name: nakama-node-1
data_dir: ./data/

logger:
  # stdout: true
  level: INFO
  file: /nakama/data/logfile.log

runtime:
  js_entrypoint: /build/main.js

session:
  token_expiry_sec: 7200 # 2 hours

console:
  port: 7351
  username: admin
  password: password
